## The following workflow is executed in two events: 
# 1. When changes are pushed to any branches in remote repository(in this case, Mock Users).
# 2. When changes are pushed to any branches in the CF automation repository.
# Manually - To trigger the workflow manually, visit github repository / actions /workflows

on:
  push:
    branches: 
      - '*'

name: Random Sanity Tests

## All jobs are executed for every workflow run
jobs:
  run_automation_tests:
    name: install cypress
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install cypress
    - run: npx cypress --help
  artifacts:
    name: create sample file and push artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: cy_install
      run: npm install cypress
    - id: test_installation
      run: echo 'abc' >>test.txt 
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: test.txt
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })