## The following workflow is executed in two events: 
# 1. When changes are pushed to any branches in remote repository(in this case, Mock Users).
# 2. When changes are pushed to any branches in the CF automation repository.
# Manually - To trigger the workflow manually, visit github repository / actions /workflows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Workflow test

## All jobs are executed for every workflow run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install cypress
      id: cypress
      run: |
        npm install cypress
        npx cypress --help
    - name: create sample image and push artifacts
      run:  curl https://www.python.org/static/apple-touch-icon-144x144-precomposed.png > image.png
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: image.png
    - uses: actions/download-artifact@v1
        with:
          name: my-artifact
    - uses: actions/github-script@v4
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '👋 Thanks for reporting!'
          })