## The following workflow is executed in two events: 
# 1. When changes are pushed to any branches in remote repository(in this case, Mock Users).
# 2. When changes are pushed to any branches in the CF automation repository.
# Manually - To trigger the workflow manually, visit github repository / actions /workflows

on:
  push:
    branches: 
      - '*'

name: Random Sanity Tests

## All jobs are executed for every workflow run
jobs:
  posts_message:
    runs-on: ubuntu-latest
    env:
      URL: ${{ github.event.pull_request.comments_url }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Add comment to PR
        run: |
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "blah blah" }'