## The following workflow is executed in two events: 
# 1. When changes are pushed to any branches in remote repository(in this case, Mock Users).
# 2. When changes are pushed to any branches in the CF automation repository.
# Manually - To trigger the workflow manually, visit github repository / actions /workflows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Random Sanity Tests

## All jobs are executed for every workflow run
jobs:
  posts_message:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })